### ISSUE TITLE
Problem mit den Sekunden

### ISSUE THREAD

**Issue by ovnn** [xSnowHeadx/lixie#1]
Mein Prinzip der Uhr ist fast das gleiche. Auf der Suche nach Software für meine bin ich auf dein repo gestoßen. Meine Ziffern sind als 0987654321 gesteckt wobei die erste und 10. LED die 0 ansteuert und die 1 die 5. und 20. LED. Er spricht immer die beiden richtigen LEDs an nur leider für die falschen Ziffern. Sprich er läuft durch die Sekunden Stelle nicht durch 0123456789 sondern springt immer durch die Zahlen. Egal welche der beiden Layouts ich von dir verwende springt er nur etwas anders. Nach meinen Verständnis müsste er ja bei dem einen Layout die leds der reihe nach durchgehen oder?

**Comment by xSnowHeadx** [comment]
Nein, die werden nicht der Reihe nach angesteuert, da sich die verwendeten Spalten immer abwechseln. So leuchten z.B. für die 1 die 5. und 15. LED, für die 2 die 7. und 17., die 3 die 2. und 12. usw.
In Deinem Fall wäre es am günstigsten, eine eigene ledmap zu verwenden. Das ist recht einfach:
die 10 binären Zahlen in der ledmap stehen von oben nach unten für die Ziffern 0 bis 9. Die 20 Ziffern nach dem "b" in jeder Zahl von rechts gezählt für die LED-Positionen in der Kette, die leuchten sollen. Suche Dir also z.B. für die 0 die beiden LED-Positionen in der Kette heraus, die leuchten sollen und trage für die in der obersten Zahl an die beiden zugehörigen Ziffernstellen (von rechts gezählt) eine 1 ein. Alle anderen Stellen müssen 0 sein. Für Deine 0 mit der 1. und 10. LED wäre die Zahl 0b00000000001000000001. Das Gleiche machst Du für die 1 mit der zweiten Zahl von oben, für die 2 mit der dritten usw.

**Comment by ovnn** [comment]
Danke hab es hinbekommen. War schon auf dem richtigen weg dachte nur das sich die 1 immer um einen verschiebt.
Meine Map schaut jetzt so aus:
static const unsigned long ledmap[10] =
{
 0b00000000010000000001,
 0b10000000001000000000,
 0b00000100000000010000,
 0b01000000000100000000,
 0b00000010000000001000,
 0b00100000000010000000,
 0b00000001000000000100,
 0b00010000000001000000,
 0b00000000100000000010,
 0b00001000000000100000, 
};

**Comment by xSnowHeadx** [comment]
Schön, daß es geklappt hat. Danke für die Rückmeldung.
